name: continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: check-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test

jobs:
  lint:
    name: code lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: prepare
        uses: ./.github/actions/prepare

      - name: lint
        run: npm run lint
  
  build:
    name: build library
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: prepare
        uses: ./.github/actions/prepare

      - name: build
        run: npm run build

  unit:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: prepare
        uses: ./.github/actions/prepare

      - name: unit
        run: npm test
